-- Inserir funcionários do setor de Varrição como Agente de limpeza
INSERT INTO public.funcionarios (nome, matricula, cargo, setor, status) VALUES
  ('ANA PAULA SILVA CASSIANO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ANDRÉ PAULO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ANTÔNIA MARIA DOS SANTOS', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ARLINDO CAITANO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('CARLOS ALEXANDRE CARVALHO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('CICERA PEREIRA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('CONCEIÇÃO MARIA SANTIAGO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('DAMIÃO JOSÉ DE OLIVEIRA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('DANIEL BARROS DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('DELZIANE GOMES DAMASCENO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('DULCINEIA JOSEFA NUNES', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EDMAR BARBOSA PINTO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EDMILSON JOSÉ DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EDNALDO DE JESUS LINDOSO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ERINALDO JOSÉ DE PAULA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('WELLINGTON BATISTA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('CLAUDEMIR VICENTE DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('GENILDA BARBOSA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('GENILDO JOSÉ DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('GISSLENO LIRA MACEDO FILHO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('SVANETE DIAS DE OLIVEIRA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JANAINA MARIA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JEREMIAS BRITO DE FIGUEREDO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOEL BARRETO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOSÉ ANTÔNIO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOSÉ BELO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOSE ERIVALDO PAULINO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOSÉ WELLINGTON DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ADJANE MARIA DA SILVA SANTOS', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EANDRA DA SILVA CAVALCANTE', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARCONES BATISTA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARIA BARBOSA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARIA BEZERRA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARIA DE FATIMA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARIA JOSE VIEIRA DE SOUZA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARIA LUCINEIDE ROQUE DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARIA MADALENA DOS SANTOS', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ROSANGELA REGIS DE OLIVEIRA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('SILVANA MARIA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ADRIANO NAZARENO FERREIRA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('CLAUDENILSON CLAUDIO BANDEIRA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('COSMO JOSE NUNES', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('CRISTINA MARIA FEITOSA TEMUDO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EDILENE GENILDA DE SOUZA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ELIAS FERREIRA LINS', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ELIZANGELA MARIA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EVERALDO JERONIMO DOS SANTOS', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EZEQUIEL PEREIRA DOS SANTOS', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('GENIVALDO JOSÉ DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('IONA FELICIANO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ISRAEL FRANCISCO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('IVANILDO CABRAL DE LIMA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOAO AMARO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOSE ROBERTO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('LUCAS JUNIOR DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MANOEL SILVA DE BARROS', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MANUEL MESSIAS DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MURILO FRANCISCO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('OZEAS COSTA GOMES', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('SEVERINO TAVARES DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('SILVANA NATALI LIMA DO NASCIMENTO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('SILVANIA MARIA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo');
