-- Inserir usuarios solicitados
INSERT INTO public.funcionarios (nome, matricula, cargo, setor, status) VALUES
  ('ADILSON PEREIRA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ALTAIR JOSE', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ANGELA MARIA DE SANTANA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('BENEDITO BARBOSA DE ARAUJO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('CICERO DA SILVA ALVES', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('CLEONICE MARIA DA CONCEIÇÃO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EDMILSON BARBOZA DO NASCIMENTO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ELIAS ROGERIO DO CARMO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('EDSON JOSE DOS SANTOS', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('FLAVIO LUIZ DA ROCHA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('GELCILENE MARIA DA CONCEIÇÃO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('IVANILDO LUIZ DA ROCHA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOABI SEVERINO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JORGE BARBOSA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JOSE AFONSO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JUNAS ANTONIO', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('JURANDIR ANTONIO VICENTE', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('LUCIANA RODRIGUES', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARCOS BARBOZA DE SOUZA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARCOS SALATIEL GOMES DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARIA JOSE DA SILVA ROCHA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('MARILENE MARIA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('PAULINA MELO DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('PAULO VICENTE QUEIROZ', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('ADEILDO BATISTA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('SANDRA SEBASTIANA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('SEVERINO PEREIRA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('SHARLENE MARIA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('TATIANA FERREIRA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('UELY OLIVEIRA DA SILVA', '', 'Agente de limpeza', 'Varrição', 'ativo'),
  ('VANDERLEY RAIMUNDO DE ALBUQUERQUE', '', 'Agente de limpeza', 'Varrição', 'ativo')
ON CONFLICT DO NOTHING;
